### ISSUE TITLE
Handle missing Meta-ID

### ISSUE THREAD

**Issue by titusz** [coblo/iscc-demo#2]
The backend might not be able to extract a title from an URL or media asset. In that case int only returns the other 3 components. Example result for url: https://raw.githubusercontent.com/iscc/iscc-cli/master/tests/image/demo.bmp

```json
{
  "iscc": "CYDfTq7Qc7Fre-CD6neyNFjpnpv-CRYUs6i9BCRWT",
  "title": "",
  "title_trimmed": "",
  "extra": null,
  "extra_trimmed": null,
  "tophash": "6e7cb529e5acf042f8480d193257625082746b24602f188d9ef8c5aba85e1750",
  "gmt": "image",
  "bits": [
    "1100001101000011001100001001111000111100100111101000111001100111",
    "0010001010011001010111111000110001001001011100001100000000001001",
    "0110111001111100101101010010100111100101101011001111000001000010"
  ]
}
```
This currently needs to be handled by the frontend. Either ask the user to provide a custom title and generate a Meta-ID or autogenerate a Meta-ID based on the captured url/file name (idealy excluding the file extension)

**Comment by Patricia92** [comment]
![image](https://user-images.githubusercontent.com/11156851/73834518-296c6b00-480c-11ea-8e19-68021d1b7d55.png)

Still no meta id when title is missing
